default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  port: 5432
  pool: 5
  host: db


development:
  <<: *default
  database: creating-an-app-from-scratch_development

test:
  <<: *default
  database: creating-an-app-from-scratch_test
